"""Add fields to Patient model for profile

Revision ID: 80e573339894
Revises: 95bd1c152c8b
Create Date: 2025-05-26 16:37:59.161712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e573339894'
down_revision = '95bd1c152c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('image_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('image_path')
        batch_op.drop_column('birthday')
        batch_op.drop_column('gender')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
