"""Added fields to doctor and fixed serialzie

Revision ID: 95bd1c152c8b
Revises: b87c8fd19ffe
Create Date: 2025-05-25 19:04:09.159412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95bd1c152c8b'
down_revision = 'b87c8fd19ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('years_of_experience', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('appointment_fee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('appointment_fee')
        batch_op.drop_column('years_of_experience')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
