"""Add listing fields and setup relationships with Reservation

Revision ID: 2fba5d10d43c
Revises: c788f733cfdd
Create Date: 2025-05-30 12:35:09.804606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fba5d10d43c'
down_revision = 'c788f733cfdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('imageSrc', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('roomCount', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bathroomCount', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('guestCount', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('locationValue', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('userId', sa.String(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('listings_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['userId'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('listingId', sa.String(), nullable=False))
        batch_op.drop_constraint(batch_op.f('reservations_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['userId'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'listings', ['listingId'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reservations_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('listingId')
        batch_op.drop_column('userId')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('listings_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('userId')
        batch_op.drop_column('price')
        batch_op.drop_column('locationValue')
        batch_op.drop_column('guestCount')
        batch_op.drop_column('bathroomCount')
        batch_op.drop_column('roomCount')
        batch_op.drop_column('category')
        batch_op.drop_column('createdAt')
        batch_op.drop_column('imageSrc')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
