"""Add reservation model fields

Revision ID: 5fe3ae9cf897
Revises: 2fba5d10d43c
Create Date: 2025-05-30 12:37:51.174615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe3ae9cf897'
down_revision = '2fba5d10d43c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startDate', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('endDate', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('totalPrice', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('createdAt')
        batch_op.drop_column('totalPrice')
        batch_op.drop_column('endDate')
        batch_op.drop_column('startDate')

    # ### end Alembic commands ###
