"""empty message

Revision ID: fa5e7ebb809f
Revises: 2bd54caa9eac
Create Date: 2025-05-22 17:13:29.387931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5e7ebb809f'
down_revision = '2bd54caa9eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_doctor_specialty'), ['specialty'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_specialty'))
        batch_op.drop_column('specialty')

    # ### end Alembic commands ###
